



server:
  port: 80

# 콘솔 ANSI 색상
spring:
  output:
    ansi:
      enabled: always

  # thymeleaf 설정
  thymeleaf:
    cache: false
    prefix: classpath:templates/views/

  # datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${rds.username}
    password: ${rds.password}

# security
  security:
    user:
       name: user1    #??? security
       password: 1234   # password

    # oauth2 client
    oauth2:
      client:
        registration:
          google:
            client-id: 460320982959-ipl76pjb3c9m42n3gtebanrjdtr99708.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 756407472985798  # 앱 ID
            client-secret: ed99b0820ad77d9f90fed97266cb2a3d  # 앱 시크릿 코드
            scope:
              - email
              - public_profile

          naver:
            client-id: PFIgGdu7CfYV8OepGYNl
            client-secret: Hmq9dAxjXf
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        #provider 제공
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  mail:
    host: smtp.gmail.com
    port: 587
    username: teamhot907@gmail.com
    password: ssjhcvtopqjrqzrg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000

mybatis:
    mapper-locations: classpath:mapper/**/*.xml

app:
  # 파일 업로드 경로
  upload:
    path: upload
  # 페이징 관련 세팅값
  pagination:
    write_pages: 10  # 기본 write_pages 값. 한 [페이징] 당 몇개의 페이지가 표시되나
    page_rows: 10   # 기본 page_rows 값.  한 '페이지'에 몇개의 글을 리스트 할것인가?


custom:
  api:
    key: 2f%2FV9qRkElbCc7j63waR%2BxKFF4CiADMtRiw%2BgCHHCCNWKS%2BlVfYVo%2FSjsfOHVlPfZcGTBHxAStYC%2FWPkqFZI9g%3D%3D

camping:
  api:
    key: W4dXNcASOsgdnixlZuchFnp2QEnLXAGMqgPGVE1Tqzxr5hRk0hk%2FNyL%2B5DDLqcmjXzU3Wp6f03aZ%2FH5gmF%2F9NA%3D%3D


weather:
  api:
    base-Url: http://apis.data.go.kr/1360000
    key: W4dXNcASOsgdnixlZuchFnp2QEnLXAGMqgPGVE1Tqzxr5hRk0hk%2FNyL%2B5DDLqcmjXzU3Wp6f03aZ%2FH5gmF%2F9NA%3D%3D
#

google:
  maps:
    api-key: AIzaSyA9awHEvUkCV6_CBwjTekEnILebtwOi8ps


kakao:
  map:
    api-key: 9e9fea9308151af194f61696a73b62fb