



server:
  port: 8080



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db907?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: user907
    password: 1234

  # thymeleaf ??
  thymeleaf:
   cache: false
   prefix: classpath:templates/views/

        # security
  security:
    user:
       name: user1    #??? security
       password: 1234   # password

mybatis:
    mapper-locations: classpath:mapper/**/*.xml

custom:
  api:
    key: vqcXGutcFTmCu%2Bmj0QWrsiStIC5kKXXSX9NCqCIU47F0OVG%2Fdf2PPck%2FWKncfjsvBo8LuNaHe2OabyzAknaHPw%3D%3D
#  uNZvaLQ2zW9vmPOCdmi1TmzKXXryvBTtrlX%2FXSXC%2FHtK31aVtIAwQaWlcS%2F2NNF8Xs271VLZTNFAUE5OUcki4Q%3D%3D
#  bKbk6RJ%2B9I%2B2vsO%2Fh5T%2FHRRah%2BN%2FMBU3z7v%2BWWWf9kgGkghBvJiY7apRsllk0cNithTfaKTWNadPPdRA%2BHB70Q%3D%3D
#  2f%2FV9qRkElbCc7j63waR%2BxKFF4CiADMtRiw%2BgCHHCCNWKS%2BlVfYVo%2FSjsfOHVlPfZcGTBHxAStYC%2FWPkqFZI9g%3D%3D
#  uNZvaLQ2zW9vmPOCdmi1TmzKXXryvBTtrlX%2FXSXC%2FHtK31aVtIAwQaWlcS%2F2NNF8Xs271VLZTNFAUE5OUcki4Q%3D%3D
#  vqcXGutcFTmCu%2Bmj0QWrsiStIC5kKXXSX9NCqCIU47F0OVG%2Fdf2PPck%2FWKncfjsvBo8LuNaHe2OabyzAknaHPw%3D%3D

camping:
  api:
    key: W4dXNcASOsgdnixlZuchFnp2QEnLXAGMqgPGVE1Tqzxr5hRk0hk%2FNyL%2B5DDLqcmjXzU3Wp6f03aZ%2FH5gmF%2F9NA%3D%3D


weather:
  api:
    base-Url: http://apis.data.go.kr/1360000
    key: W4dXNcASOsgdnixlZuchFnp2QEnLXAGMqgPGVE1Tqzxr5hRk0hk%2FNyL%2B5DDLqcmjXzU3Wp6f03aZ%2FH5gmF%2F9NA%3D%3D
# sGbdgmLo3C0njpf5eegGGxzj8QuTtBy0RsGILKRhnz7yFyLXKDoeODGcbvud%2FV5Lymd%2Fzc3eUBgehm2F1poEaQ%3D%3D
#

google:
  maps:
    api-key: AIzaSyA9awHEvUkCV6_CBwjTekEnILebtwOi8ps


#  AIzaSyA9awHEvUkCV6_CBwjTekEnILebtwOi8ps